version: "3.9"

volumes:
  point-quest-postgres-data:

services:
  postgres:
    container_name: point-quest-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    restart: always
    volumes:
      - point-quest-postgres-data:/var/lib/postgresql/data
    ports:
      - 5430:5432
