# fly.toml app configuration file generated for pointquest on 2024-03-16T14:33:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pointquest'
primary_region = 'mia'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'pointquest.fly.dev'
  DNS_CLUSTER_QUERY = 'pointquest.internal'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
